proj/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LogoutView, PasswordChangeDoneView,
    PasswordResetDoneView, PasswordResetCompleteView
)

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('login/', views.LoginView.as_view(), name='login'),
    path(
        'password_change/',
        views.UserPasswordChange.as_view(template_name='account/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password-change/done/',
        PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),
        name='password_change_done'
    ),

    path(
        'password_reset/',
        views.UserPasswordResetView.as_view(template_name='account/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
        name='password_reset_done'
    ),

    path(
        'reset/<uidb64>/<token>/',
        views.UserPasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
        name='password_reset_complete'
    ),


    path('personal_account_main/', views.personal_account_main, name='personal_account_main'),
    path('order/', views.order, name='order'),
    path('order/done/', views.order_done, name='order_done'),

    path('rating/', views.rating, name='rating'),
]

proj/courses/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('index/', views.index, name='index'),
    path('all_courses/', views.all_courses, name='all_courses'),
    path('all_courses/<slug:slug>/', views.category_courses, name='category_courses'),
    path('course/<slug:slug>/', views.course, name='course'),
    path('problem/<int:problem_id>/', views.problem, name='problem'),
    path('tournament/', views.tournament, name='tournament'),
    path('tournament_problem/<int:problem_id>/', views.tournament_problem, name='tournament_problem'),
    path('current_courses/', views.current_courses, name='current_courses'),
    path('completed_courses/', views.completed_courses, name='completed_courses'),
    path('personal_courses/', views.personal_courses, name='personal_courses'),
    path('personal_course/<slug:slug>/', views.personal_course, name='personal_course'),
    path('personal_problem/<int:problem_id>/', views.personal_problem, name='personal_problem'),
]

proj/proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve as mediaserve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('account/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]
    

proj/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from account.models import CustomUser
from courses.models import Category, Course, CourseProblem, PersonalCourse, PersonalProblem, Tournament, \
    TournamentProblem
from datetime import date
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Window, F
from django.db.models.functions import Rank


def index(request):
    return render(request, 'courses/index.html')


def all_courses(request):
    categories = Category.objects.all()
    categories_with_courses = []

    # Формируем список категорий с 4 курсами для каждой категории
    for category in categories:
        courses = Course.objects.filter(category=category).order_by('title')[:4]
        categories_with_courses.append({
            'category': category,
            'courses': courses
        })

        # Получаем 3 курса, где первая задача решена, а последняя нет
        current_courses_list = []

        # Проверка на авторизацию пользователя
        if request.user.is_authenticated:
            user = request.user

            all_course_obj = Course.objects.all().order_by('title')

            for course_obj in all_course_obj:
                # Определяем первую и последнюю задачу по номеру в курсе
                first_problem = CourseProblem.objects.filter(course=course_obj).order_by('number').first()
                last_problem = CourseProblem.objects.filter(course=course_obj).order_by('number').last()

                # Проверяем условия: первая решена, а последняя - нет
                if first_problem and last_problem:
                    if (
                            first_problem in user.solved_problems.all()
                            and last_problem not in user.solved_problems.all()
                    ):
                        current_courses_list.append(course_obj)
                        if len(current_courses_list) == 3:
                            break

    context = {
        'categories_with_courses': categories_with_courses,
        'current_courses': current_courses_list,
        'current_date': date.today(),
    }
    return render(request, 'courses/all_courses.html', context)


def category_courses(request, slug):
    category = get_object_or_404(Category, slug=slug)
    courses = Course.objects.filter(category=category).order_by('title')
    context = {
        'category': category,
        'courses': courses,
    }
    return render(request, 'courses/category_courses.html', context)


def course(request, slug):
    course_obj = get_object_or_404(Course, slug=slug)
    if not course_obj.free:
        if (request.user.is_authenticated and request.user.end_of_subscription and
                request.user.end_of_subscription >= date.today()):
            problems = CourseProblem.objects.filter(course=course_obj).order_by('number')
            notification = None
        else:
            problems = None
            notification = "Курс доступен по подписке"
    else:
        problems = CourseProblem.objects.filter(course=course_obj).order_by('number')
        notification = None
    context = {
        'course': course_obj,
        'problems': problems,
        'notification': notification,
    }
    return render(request, 'courses/course.html', context)


def problem(request, problem_id):
    problem_obj = get_object_or_404(CourseProblem, pk=problem_id)
    problem_obj_course = problem_obj.course

    if (problem_obj_course.free or (
            not problem_obj_course.free and request.user.is_authenticated and request.user.end_of_subscription and
            request.user.end_of_subscription >= date.today())):
        notification = None
        try:
            next_problem = CourseProblem.objects.get(course=problem_obj_course,number=problem_obj.number+1)
            next_problem_id = next_problem.pk
        except:
            next_problem_id = None
        if request.method == 'POST':
            selected_answer = request.POST.get('answer')  # получаем ответ, выбранный пользователем
            if selected_answer:
                try:
                    selected_answer = int(selected_answer)  # проверяем, что ответ - это число
                    if selected_answer == problem_obj.right_answer:
                        if request.user.is_authenticated and problem_obj not in request.user.solved_problems.all():
                            # Если ответ правильный и задача решается парвый раз, начисляем пользователю очки
                            request.user.points += problem_obj.points
                            request.user.solved_problems.add(problem_obj)
                            request.user.save()
                        messages.success(request, 'Молодец! Ответ правильный. Приступим к следующему вопросу?')
                    else:
                        messages.error(request, 'Увы, но ответ неверный. Попробуешь еще раз ?')
                except ValueError:
                    messages.error(request, 'Увы, но ответ неверный. Попробуешь еще раз ?')
            else:
                messages.error(request, 'Ты не выбрал ответ. Попробуешь еще раз ?')
    else:
        notification = "Курс доступен по подписке"
        next_problem_id = None
    context = {
        'problem_obj': problem_obj,
        'next_problem_id': next_problem_id,
        'notification': notification,
    }
    return render(request, 'courses/problem.html', context)


def tournament(request):
    today = date.today()
    try:
        tournament_obj = Tournament.objects.get(end_date__gte=today,start_date__lte=today)
    except:
        tournament_obj = None
    all_tournament_top_users = CustomUser.objects.all().annotate(
        rank=Window(
            expression=Rank(),
            order_by=F('tournament_points').desc()
        )
    ).order_by('-tournament_points')   

    tournament_top_users = all_tournament_top_users[:10]

    if request.user.is_authenticated and tournament_obj and request.user in tournament_obj.participants.all():
        tournament_problems = TournamentProblem.objects.filter(tournament=tournament_obj).order_by('number')
        notification = None
        # Ищем позицию авторизованного пользователя
        user_position_in_tournament_top = all_tournament_top_users.get(id=request.user.id).rank
    else:
        tournament_problems = None
        notification = "Участвуй и стань лучшим!"
        user_position_in_tournament_top = None
    context = {
        'tournament_obj': tournament_obj,
        'tournament_top_users': tournament_top_users,
        'tournament_problems': tournament_problems,
        'notification': notification,
        'user_position_in_tournament_top': user_position_in_tournament_top,
    }
    return render(request, 'courses/tournament.html', context)


@login_required
def tournament_problem(request, problem_id):
    today = date.today()
    user = request.user
    problem_obj = get_object_or_404(TournamentProblem, pk=problem_id)
    problem_obj_tournament = problem_obj.tournament

    if (problem_obj_tournament and
            problem_obj_tournament.end_date >= today >= problem_obj_tournament.start_date and
            user in problem_obj_tournament.participants.all()):
        try:
            next_problem = TournamentProblem.objects.get(course=problem_obj_tournament,number=problem_obj.number+1)
            next_problem_id = next_problem.pk
        except:
            next_problem_id = None

        if request.method == 'POST':
            selected_answer = request.POST.get('answer')  # получаем ответ, выбранный пользователем
            if selected_answer:
                try:
                    selected_answer = int(selected_answer)  # проверяем, что ответ - это число
                    if (selected_answer == problem_obj.right_answer and
                            problem_obj not in user.solved_tournament_problems.all()):
                        # Если ответ правильный и задача решается парвый раз,
                        # начисляем пользователю очки турнира и обычные + добавляем в решенные
                        request.user.tournament_points += problem_obj.points
                        request.user.points += problem_obj.points
                        request.user.solved_tournament_problems.add(problem_obj)
                        request.user.save()
                        messages.success(request, 'Ответ засчитан! Приступим к следующему вопросу?')
                    elif (selected_answer != problem_obj.right_answer and
                            problem_obj not in user.solved_tournament_problems.all()):
                        # Если ответ не правильный и задача решается парвый раз,
                        # добавляем в решенные
                        request.user.solved_tournament_problems.add(problem_obj)
                        request.user.save()
                        messages.success(request, 'Ответ засчитан! Приступим к следующему вопросу?')
                    else:
                        messages.error(request, 'Эй! Ты уже отвечал! Так не считается!😝')
                except ValueError:
                    messages.error(request, 'Не могу прочитать ответ... Попробуешь еще раз ?')
            else:
                messages.error(request, 'Ты не выбрал ответ. Попробуешь еще раз ?')
    else:
        return redirect('tournament', )

    context = {
        'problem_obj': problem_obj,
        'next_problem_id': next_problem_id,
    }
    return render(request, 'courses/tournament_problem.html', context)


@login_required
def current_courses(request):
    current_courses_list = []

    # Проверка на авторизацию пользователя
    if request.user.is_authenticated:
        user = request.user

        # Получаем все экземпляры PersonalCourse, где первая задача решена, а последняя нет
        all_personal_course_obj = PersonalCourse.objects.all().order_by('title')
        for personal_course_obj in all_personal_course_obj:

proj/templates/courses/all_courses.html
{% extends 'base.html' %}
{% block title %}
Курсы
{% endblock %}

{% block content %}
{% load static %}
<main>
    <div class="courses-container">
        <h2>Текущие курсы</h2>
        <ul class="account-course-block-elements lakki-reddy-regular" style="max-width:800px;">
            {% for course in current_courses %}
                <li class="course-element" style="background-image: url({{ course.image.url }}); background-size: 100% 100%; cursor:pointer;" onclick="location.href='{% url 'course' course.slug %}'">
                    <p><span class="labrada-regular account-course-text-elements" style="color: #000000; font-size: 20px;">{{ course.title }}</span></p>
                </li>
            {% endfor %}
            <li style="background: rgba(246, 246, 246, 1); width:auto; height:50px; align-items: unset;">
                <a href="{% url 'current_courses' %}" rel="noopener">
                    <img src="{% static 'img/Arrow right.png' %}">
                </a>
            </li>
        </ul>

        {% for item in categories_with_courses %}
            <h2>{{ item.category.title }}</h2>
            <ul class="account-course-block-elements lakki-reddy-regular" style="max-width:800px;">
                {% for course in item.courses %}
                    {% if course.free or current_date <= request.user.end_of_subscription %}
                    <li class="course-element" style="background-image: url({{ course.image.url }}); background-size: 100% 100%; cursor:pointer;" onclick="location.href='{% url 'course' course.slug %}'">
                        <p><span class="labrada-regular account-course-text-elements" style="color: #000000; font-size: 20px;">{{ course.title }}</span></p>
                    </li>
                    {% else %}
                    <li class="course-element" style="background-image: url({{ course.image.url }}); background-size: 100% 100%; opacity: 0.5;">
                        <p><span class="labrada-regular account-course-text-elements" style="color: #000000; font-size: 20px;">{{ course.title }}</span></p>
                    </li>
                    {% endif %}
                {% endfor %}
                <li style="background: rgba(246, 246, 246, 1); width:auto; height:50px; align-items: unset;">
                    <a href="{% url 'category_courses' item.category.slug %}" rel="noopener">
                        <img src="{% static 'img/Arrow right.png' %}">
                    </a>
                </li>
            </ul>
        {% endfor %}
    </div>
    <img src="{% static 'img/bg-account.png' %}" id="lastimage" class="side-image" style="top:35%; height: auto; z-index: -1; transform: unset;">
</main>
{% endblock %}

proj/templates/courses/category_courses.html
{% extends 'base.html' %}
{% block title %}
{{ category.title }}
{% endblock %}

{% block content %}
{% load static %}
<main>
    <div class="courses-container">
        <h2>{{ category.title }}</h2>
        <ul class="account-course-block-elements lakki-reddy-regular" style="max-width:800px;">
            {% for course in courses %}
                {% if course.free or current_date <= request.user.end_of_subscription %}
                <li class="course-element" style="background-image: url({{ course.image.url }}); background-size: 100% 100%; cursor:pointer;" onclick="location.href='{% url 'course' course.slug %}'">
                        <p><span class="labrada-regular account-course-text-elements" style="color: #000000; font-size: 20px;">{{ course.title }}</span></p>
                </li>
                {% else %}
                <li class="course-element" style="background-image: url({{ course.image.url }}); background-size: 100% 100%; cursor:pointer;">
                        <p><span class="labrada-regular account-course-text-elements" style="color: #000000; font-size: 20px;">{{ course.title }}</span></p>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
    <img src="{% static 'img/bg-account.png' %}" id="lastimage" class="side-image" style="top:35%; height: auto; z-index: -1; transform: unset;">
</main>
{% endblock %}

proj/templates/courses/completed_courses.html
{% extends 'base.html' %}
{% block title %}
Пройденные курсы
{% endblock %}

{% block content %}
{% load static %}
<main>
{% load custom_filters %}
<div class="courses-container">
    <h2>Пройденные курсы</h2>
    <ul class="account-course-block-elements lakki-reddy-regular" style="max-width:800px;">
        {% for course in completed_courses_list %}
            <li class="course-element" style="background-image: url({{ course.image.url }}); background-size: 100% 100%; cursor:pointer;" onclick="location.href='{% url 'course' course.slug %}'">
                {% if course|is_instance:"Course" %}
                    <!-- Ссылка для Course -->
                    <a href="{% url 'course' course.slug %}" style="text-decoration:none;">
                        <p>
                            <span class="labrada-regular account-course-text-elements" style="color: #000000; font-size: 20px;">
                                {{ course.title }}
                            </span>
                        </p>
                    </a>
                {% elif course|is_instance:"PersonalCourse" %}
                    <!-- Ссылка для PersonalCourse -->
                    <a href="{% url 'personal_course' course.slug %}" style="text-decoration:none;">
                        <p>
                            <span class="labrada-regular account-course-text-elements" style="color: #000000; font-size: 20px;">
                                {{ course.title }}
                            </span>
                        </p>
                    </a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</div>
</main>
{% endblock %}

proj/templates/courses/course.html
{% extends 'base.html' %}
{% block title %}
Курс | {{ course.title }}
{% endblock %}

{% block content %}
{% load static %}
<main>
    <div class="courses-container">
        <a href="{{ request.META.HTTP_REFERER }}" rel="noopener" class="button button--outlined labrada-regular" style="margin-top: 20px;">
            <span>Вернуться назад</span>
        </a>
        <h1>Курс: {{ course.title }}</h1>
        <!--ЕСЛИ ПОДПИСКА НЕ ДЕЙСТВУЕТ ВЫДАЕМ ТЕКСТ С УВЕДОМЛЕНИЕМ ИЗ КОНТЕКСТА-->
        {% if notification %}
        {{ notification }}
        {% endif %}

        <!--ЕСЛИ ПОДПИСКА НЕ ДЕЙСТВУЕТ ЭЛЕМЕНТОВ В ЦИКЛЕ ПРОСТО НЕ БУДЕТ,
        ДЕЙСТВУЕТ - ВЫВОДИТ ЗАДАЧИ ИЗ КОНТЕКСТА-->
        <div style="width:100%;">
        <ul class="course-task-block-elements lakki-reddy-regular" style="display: flex; flex-wrap: wrap;">
        {% for problem in problems %}
            <li class="course-element">
                <a href="{% url 'problem' problem.pk %}" rel="noopener" class="button button--outlined labrada-regular">
                <p>
                    <span>
                        Задача №{{ problem.number }}
                    </span>
                </p>
                </a>
            </li>
        {% endfor %}
        </ul>
        </div>
    </div>
</main>
{% endblock %}

proj/templates/courses/current_courses.html
{% extends 'base.html' %}
{% block title %}
Текущие курсы
{% endblock %}

{% block content %}
{% load static %}
<main>
    <div class="courses-container">
        <h2>Текущие курсы</h2>
        <ul class="account-course-block-elements lakki-reddy-regular" style="max-width:800px;">
            {% for course in current_courses_list %}
                <li class="course-element" style="background-image: url({{ course.image.url }}); background-size: 100% 100%; cursor:pointer;" onclick="location.href='{% url 'course' course.slug %}'">
                    <p><span class="labrada-regular account-course-text-elements" style="color: #000000; font-size: 20px;">{{ course.title }}</span></p>
                </li>
            {% endfor %}
        </ul>
    </div>
    <img src="{% static 'img/bg-account.png' %}" id="lastimage" class="side-image" style="top:35%; height: auto; z-index: -1; transform: unset;">
</main>
{% endblock %}

proj/templates/courses/index.html
{% extends 'base.html' %}
{% block title %}
Главная
{% endblock %}

{% block content %}
{% load static %}

<main>
<div>
  <div class="kl-rich-text--center" style="background-color:#F8F9FB;">
        <ul class="first-block lakki-reddy-regular">
            <li>
                <h1><span style="color: #734D91; font-weight: bold;" class="main-text">Мир знаний в<br>твоем экране</span></h1>
                <p><span style="color: #000000; font-size: 20px; font-weight: bold;">Учись, играя, и стань лучшим!</span></p>
            </li>
            <li>
                <img style="max-width: 75vw;" src="{% static 'img/mainimg.png' %}">
            </li>
        </ul>
      <img src="{% static 'img/bg1.png' %}" class="side-image">
  </div>

    <div class="kl-rich-text--center" style="padding-top:30px;">
            <ul class="second-block lakki-reddy-regular" style="max-width:800px;">
                <li style="background-color:#8D58A1;">
                    <p><span style="color: #ffffff; font-size: 22px">Обучение как игра</span></p>
                    <hr class="color-blocks-line">
                    <p><span style="color: #ffffff; font-size: 20px">Уровни, очки опыта и топ игроков</span></p>
                </li>
                <li style="background-color:#FA8C3F;">
                    <p><span style="color: #ffffff; font-size: 22px">Большой выбор курсов</span></p>
                    <hr class="color-blocks-line">
                     <p><span style="color: #ffffff; font-size: 20px">Математика, русский, логика, творческое мышление и множество другого</span></p>
                </li>
                <li style="background-color:#F34F69;">
                    <p><span style="color: #ffffff; font-size: 22px">Сезонные турниры</span></p>
                    <hr class="color-blocks-line">
                     <p><span style="color: #ffffff; font-size: 20px">Веселые соревнования для самых крутых</span></p>
                </li>
                <li style="background-color:#00B5F3;">
                    <p><span style="color: #ffffff; font-size: 22px">Лояльные цены</span></p>
                    <hr class="color-blocks-line">
                     <p><span style="color: #ffffff; font-size: 20px">Куча курсов по цене шоколадки</span></p>
                </li>
            </ul>
        <img src="{% static 'img/bg2.png' %}" class="side-image" style="left:0; top:100%; height: auto; max-height: 100vw; z-index: -1;">
  </div>

    <div class="third-block-container">
        <ul class="third-block lakki-reddy-regular">
            <li>
                <img src="{% static 'img/kidimg1.png' %}" style="max-width: 80vw;">
            </li>
            <li>
                <p><span class="labrada-regular" style="color: #734D91; font-size: 30px; font-weight: bold;">Хочешь индивидуальный курс?</span></p>
                <p><span style="color: #000000; font-size: 20px">Наши специалисты составят программу специально для тебя!</span></p>
                <a href="{% url 'account:order' %}" rel="noopener" class="button button--outlined labrada-regular">
                    <span>Подобрать курс</span>
                </a>
            </li>
        </ul>
        <ul class="third-block lakki-reddy-regular" style="width:100%;justify-content:space-between;">
            <li>
                <p><span class="labrada-regular" style="color: #734D91; font-size: 30px; font-weight: bold;">Начни игру!</span></p>
                <p><span style="color: #000000; font-size: 20px">Наши курсы уже ждут тебя!</span></p>
                <a href="{% url 'all_courses' %}" rel="noopener" class="button button--outlined labrada-regular">
                    <span>Попробовать себя</span>
                </a>
            </li>
            <li>
                <img src="{% static 'img/kidimg2.png' %}" style="max-width: 80vw;">
            </li>
        </ul>
  </div>

    <div class="kl-rich-text--center last-block">
        <div class="banner">
            <p>Здесь будет баннер партнеров.</p>
        </div>
        <ul class="third-block lakki-reddy-regular" style="max-width:800px;width:100%;justify-content:space-between;">
            <li>
                <p><span class="labrada-regular" style="color: #734D91; font-size: 30px; font-weight: bold;">Порадуй себя вместе с нашими партнерами</span></p>
                <p><span style="color: #000000; font-size: 20px">Магазин канцтоваров для учебы и творчества!</span></p>
                <a href="" target="_blank" rel="noopener" class="button button--outlined labrada-regular">
                    <span>Посмотреть</span>
                </a>
            </li>
            <li>
                <img src="{% static 'img/orig.png' %}" style="max-width: 80vw;">
            </li>
        </ul>
       <img src="{% static 'img/math1.png' %}"  id="lastimage" class="side-image" style="top:0; height: auto; z-index: -1; transform: translateY(-25%);">
  </div>
</div>
</main>

{% endblock %}

proj/templates/courses/personal_course.html
{% extends 'base.html' %}
{% block title %}
Курс | {{ course.title }}
{% endblock %}

{% block content %}
{% load static %}
<main>
    <div class="courses-container">
        <a href="{{ request.META.HTTP_REFERER }}" rel="noopener" class="button button--outlined labrada-regular" style="margin-top: 20px;">
            <span>Вернуться назад</span>
        </a>
        <h1>Курс: {{ course.title }}</h1>

        <div style="width:100%;">
        <ul class="course-task-block-elements lakki-reddy-regular" style="display: flex; flex-wrap: wrap;">
        {% for problem in problems %}
            <li class="course-element">
                <a href="{% url 'personal_problem' problem.pk %}" rel="noopener" class="button button--outlined labrada-regular">
                <p>
                    <span>
                        Задача №{{ problem.number }}
                    </span>
                </p>
                </a>
            </li>
        {% endfor %}
        </ul>
        </div>
    </div>
</main>
{% endblock %}

proj/templates/courses/tournament.html
{% extends 'base.html' %}
{% block title %}
Турниры
{% endblock %}

{% block content %}
{% load static %}
<main>
    <div class="tournament" style="min-height: 100vh;">
        <h1>«{{tournament_obj.title}}»</h1>
        {% if not request.user.is_authenticated%}
        <a href="{% url 'account:order' %}" class="button button--outlined labrada-regular" style="margin-top: 15px;">Участвовать</a>
        {% endif %}
        <div class="date-container">
            <p><span>Будет проходить до {{tournament_obj.end_date|date:"d.m.Y"}}</span></p>
        </div>

        {% if not notification %}
            <h2 style="text-align: center;">Задачи</h2>
            <div>
            <ul class="tournament-task lakki-reddy-regular" style="display: flex; flex-wrap: wrap;">
            {% for tournament_problem in tournament_problems %}
                <li>
                    <a href="{% url 'tournament_problem' tournament_problem.pk %}" rel="noopener" class="button button--outlined labrada-regular">
                        <p>
                            <span>
                                Задача №{{ tournament_problem.number }}
                            </span>
                        </p>
                    </a>
                </li>
            {% endfor %}
            </ul>
            </div>
        {% endif %}
        <div style="margin-top: 50px;">
            <ul class="tournament-member-list">
                {% for user in tournament_top_users %}
                    <li style="background:
                        {% if forloop.counter == 1 %} rgba(255, 215, 0, 1)
                        {% elif forloop.counter == 2 %} rgba(204, 204, 204, 1)
                        {% elif forloop.counter == 3 %} rgba(201, 114, 34, 1)
                        {% else %} rgba(235, 235, 235, 1);
                        {% endif %}">
                        <div class="tournament-member-block">
                            <p>
                                <span>{{ forloop.counter }}</span>
                            </p>
                            <img src="{% static 'img/avatar.png' %}" alt="logo" style="max-width: 30px; max-height: 30px">
                            <p>
                                <span>{{ user.username }}</span>
                            </p>
                        </div>
                        <p style="margin-right: 15px;">
                            <span>Очков: {{user.tournament_points}}</span>
                        </p>
                    </li>
                {% endfor %}
            </ul>
            {% if request.user.is_authenticated%}
            <ul class="tournament-member-list" style="margin-top: 50px;">
                    <li>
                        <div class="tournament-member-block">
                            <p>
                                <span>{{ user_position_in_tournament_top }}</span>
                            </p>
                            <img src="{% static 'img/avatar.png' %}" alt="logo" style="max-width: 30px; max-height: 30px">
                            <p>
                                <span>{{ request.user }}</span>
                            </p>
                        </div>
                        <p style="margin-right: 15px;">
                            <span>Очков: {{request.user.tournament_points}}</span>
                        </p>
                    </li>
            </ul>
            {% endif %}
        </div>
        </div>
</main>
{% endblock %}