proj/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('our_team/', views.our_team, name='our_team'),
    path('contacts/', views.contacts, name='contacts'),
    path('faq/', views.faq, name='faq'),
]

proj/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LogoutView, PasswordChangeDoneView,
    PasswordResetDoneView, PasswordResetCompleteView
)

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('login/', views.LoginView.as_view(), name='login'),
    path(
        'password_change/',
        views.UserPasswordChange.as_view(template_name='account/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password-change/done/',
        PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),
        name='password_change_done'
    ),

    path(
        'password_reset/',
        views.UserPasswordResetView.as_view(template_name='account/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
        name='password_reset_done'
    ),

    path(
        'reset/<uidb64>/<token>/',
        views.UserPasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
        name='password_reset_complete'
    ),


    path('personal_account_main/', views.personal_account_main, name='personal_account_main'),
    path('order/', views.order, name='order'),
    path('order/done/', views.order_done, name='order_done'),

    path('rating/', views.rating, name='rating'),
]

proj/proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve as mediaserve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('account/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]
    

proj/templates/includes/footer.html
{% load static %}

<div class="kl-footer__wrapper content-wrapper">
    <div class="kl-footer__content">
          <div class="kl-footer__menu">
          <div class="kl-footer__group">
			<h3>Информация</h3>
            <ul>
                <li>
                  <a href="{% url 'about:faq' %}">FAQ</a>
                </li>
                <li>
                  <a href="{% url 'about:our_team' %}">О нас</a>
                </li>
            </ul>
          </div>

          <div class="kl-footer__group">
			<h3>Контакты</h3>
            <ul>
                <li>
                  <a target="_blank" href="mailto:nikitafofilov08@gmail.com">nikitafofilov08@gmail.com</a>
                </li>
                <li>
                  <a target="_blank" href="tel:79023810051">+7-902-381-00-51</a>
                </li>
            </ul>
          </div>
          <div class="kl-footer__group">
			<h3>Чат с поддержкой</h3>
            <ul class="kl-footer-ul__flex">
                <li>
                  <a href="https://t.me/latungamon" target="_blank">
                    <img src="{% static 'img/tglogo.png' %}" alt="telegram" class="kl-footer__img" style="max-width: 54px; max-height: 54px;">
                  </a>
                </li>
                <li>
                  <a href="https://vk.com/4ndgc" target="_blank">
                    <img src="{% static 'img/vklogo.png' %}" alt="vk" class="kl-footer__img">
                  </a>
                </li>
            </ul>
          </div>
      </div>
    </div>
    <div class="kl-footer__legal">
      <span>© SuperBrain, 2024</span>
    </div>
</div>

proj/templates/includes/header.html
{% load static %}

<nav class="kl-navbar content-wrapper">
    <div class="navbar-container">
        <div class="main-header">
            <a href="{% url 'index' %}">
                <img src="{% static 'img/logo.png' %}" alt="logo" width="100%" style="max-width: 80px; max-height: 80px" class="kl-navbar__logo">
            </a>
            <div class="kl-navbar__content">
                <ul class="kl-navbar__menu">
                    <li class="kl-navbar__item kl-navbar__parent">
                        <a class="kl-navbar__button labrada-regular" href="{% url 'all_courses' %}">
                            <span>Курсы</span>
                        </a>
                    </li>
                    <li class="kl-navbar__item">
                        <a class="kl-navbar__button labrada-regular" href="{% url 'tournament' %}">
                            <span>Турнир</span>
                        </a>
                    </li>
                    <li class="kl-navbar__item">
                        <a class="kl-navbar__button labrada-regular" href="{% url 'account:rating' %}">
                            <span>Рейтинг</span>
                        </a>
                    </li>
                </ul>
                {% if not request.user.is_authenticated %}
                <div class="kl-navbar__end">
                    <a href="{% url 'account:login' %}" rel="noopener" class="button button--outlined labrada-regular">
                        <span>Войти</span>
                    </a>
                </div>
                {% else %}
                <div class="kl-navbar__end">
                    <a href="{% url 'account:personal_account_main' %}" rel="noopener" class="labrada-regular" style="display: flex
;
    justify-content: center;
    align-items: center;
    color: black;">
                        <span>Вы вошли как {{ request.user }}</span>
                        <img src="{% static 'img/avatar.png' %}" style="max-width: 50px; margin-left: 10px;">
                    </a>
                </div>
                {% endif %}

                <!-- Иконка бургера для мобильных устройств -->
                <div class="kl-navbar__burger" id="burger-icon">
                    <span class="kl-navbar__burger-line"></span>
                    <span class="kl-navbar__burger-line"></span>
                    <span class="kl-navbar__burger-line"></span>
                </div>
            </div>
        </div>
    </div>
</nav>

<!-- Мобильное меню -->
<div class="kl-navbar__mobile-menu" id="mobile-menu">
    <ul class="kl-mobile__menu">
        <li class="kl-navbar__item">
            <a class="kl-navbar__button labrada-regular" href="{% url 'all_courses' %}">
                <span>Курсы</span>
            </a>
        </li>
        <li class="kl-navbar__item">
            <a class="kl-navbar__button labrada-regular" href="{% url 'tournament' %}">
                <span>Турнир</span>
            </a>
        </li>
        <li class="kl-navbar__item">
            <a class="kl-navbar__button labrada-regular" href="{% url 'account:rating' %}">
                <span>Рейтинг</span>
            </a>
        </li>
        <li class="kl-navbar__item">
            {% if not request.user.is_authenticated %}
                    <a href="{% url 'account:login' %}" rel="noopener" class="button button--outlined labrada-regular">
                        <span>Войти</span>
                    </a>
                {% else %}
                    <a href="{% url 'account:personal_account_main' %}" rel="noopener" class="labrada-regular" style="display: flex
;
    align-items: center;
    color: black;">
                        <span>Вы вошли как {{ request.user }}</span>
                        <img src="{% static 'img/avatar.png' %}" style="max-width: 50px; margin-left: 10px;">
                    </a>
                {% endif %}
        </li>
    </ul>
</div>

<script>
    document.getElementById('burger-icon').addEventListener('click', function() {
        var mobileMenu = document.getElementById('mobile-menu');
        mobileMenu.classList.toggle('open');
    });
</script>